### ISSUE TITLE
Error: The background page is not responding

### ISSUE THREAD

**Issue by JordyScript** [tim-we/tabs-aside#66]
After using version 3 for a while without problems, suddenly the sidebar gives the following error, and no longer shows any saved sessions: 

![firefox_2020-02-05_13-09-22](https://user-images.githubusercontent.com/35542866/73840620-da790280-4818-11ea-82d8-6305a487798b.png)

Clicking "Try again" doesn't fix the issue. Disabling and re-enabling the add-on didn't work either. Same for uninstalling and reinstalling.

Do you have any clue how this happened or how it can be fixed?

**Comment by tim-we** [comment]
That is odd. What version of Firefox are you using? Does the options page still work? Can you go to `about:debugging` > This Firefox > Tabs Aside > Inspect and see if there are any additional error logs in the console?

**Comment by JordyScript** [comment]
Firefox version: 72.0.2 (64-bit)

This is the error log:
[tabs-aside_console_error_log.txt](https://github.com/tim-we/tabs-aside/files/4159511/tabs-aside_console_error_log.txt)

**Comment by tim-we** [comment]
Hmm so far I was unable to reproduce that error. Besides the console there should also be a Storage tab. I am interested in what is stored in the Extension Storage, especially the value of `options`, `setup` and `version`.
Some other stuff you could try switching to another session root folder (and then back) or uninstalling and reinstalling (this should remove the extension storage, disabling does not).

**Comment by JordyScript** [comment]
So, I've already tried uninstalling and reinstalling (multiple times) before I opened this issue, which did not seem to fix it. 

This is my extension storage: 
Version: 2
setup: true
options: {"rootFolder":"g2I2kKUr2fQR"}

Changing the root folder in options doesn't seem to work either.

**Comment by tim-we** [comment]
By any chance does manually opening & closing the sidebar help? What other extensions do you have installed? In that error log was this line `Error: Bookmark not found undefined`, can you see the file that causes this?

**Comment by JordyScript** [comment]
I deactivated and subsequently reactivated the extension and immediately tried reloading the extension. These were the errors i got, but there was no filename after Bookmark not found. In place of where the filename would be, it said: undefined.

```
Webconsole context has changed
[TA] Failed to send reload command to sidebar. Error: "Could not establish connection. Receiving end does not exist."
    <anonymous> moz-extension://92ba02e1-5ed4-45f9-810a-0ab916947daa/js/background/background.js:34
background.js:35:25
Error: Bookmark not found undefined
Firefox can’t establish a connection to the server at ws://127.0.0.1:12546/. app.js:2068:29
Error: Invalid window ID: -1 ExtensionUtils.jsm
```

However, now I do have an idea of what might have caused it. I accidentally set aside a window with pinned tabs, which closed the entire window and a new window with a blank tab got automatically opened. This was not what i wanted, so i reopened the closed window (history > recently closed windows > window), deleted the tab group, and closed the newly opened window. Maybe that has something to do with the ```Invalid window ID``` in the log.

As far as extensions are concerned, I had experimented with an extension called [Tab Manager Plus for Firefox](https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox) to organize my tabs into windows before setting them aside. All other extensions haven't changed in a long time.

**Comment by JordyScript** [comment]
Oh, and i since removed the extension, but that didn't solve the problem either.

**Comment by tim-we** [comment]
You were right, at startup Tabs Aside checks existing windows/tabs if they are part of an active session. The tabs you have restored via history > recently closed windows > window have the active session flag set but the session/bookmark does not exist anymore.

**Comment by tim-we** [comment]
I published a new version on AMO, can you please update the extension and confirm that the issue is fixed?

**Comment by JordyScript** [comment]
Thanks for looking into it! I installed the new version, but I still get the same error, unfortunately.

**Comment by tim-we** [comment]
Sorry I should have checked more thoroughly. It should be fixed now as I could reproduce the bug.

**Comment by tim-we** [comment]
New version is live, please try again :)

**Comment by JordyScript** [comment]
You are right ! It is fixed. Thank you very much :) This is a great extension.

**Comment by tim-we** [comment]
Thanks! And sorry for causing this inconvenience in the first place.
